apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "50%"
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        imagePullPolicy: IfNotPresent
        image: movierama/ui
        ports:
        - containerPort: 80
          name: ui
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
  - port: 8080
    targetPort: 80
    name: ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui
                port:
                  number: 8080
