apiVersion: v1
kind: Service
metadata:
  name: tb-redis
spec:
  ports:
  - name: tb-redis-port
    port: 6379
  selector:
    app: tb-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-redis
spec:
  selector:
    matchLabels:
      app: tb-redis
  template:
    metadata:
      labels:
        app: tb-redis
    spec:
      containers:
      - image: redis:4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        name: server
        ports:
        - containerPort: 6379
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-data
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: redis-data
