apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "50%"
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      initContainers:
      - name: ratings-deploy
        image: "ghcr.io/groundnuty/k8s-wait-for:v1.6"
        args: [ "job", "db-init" ]
      containers:
      - name: ratings
        imagePullPolicy: IfNotPresent
        image: movierama/app
        command: [ "npm" ]
        args: [ "run", "ratings" ]
        ports:
        - containerPort: 8080
          name: ratings
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: DB_HOST
          value: "tb-database"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "postgres"
        - name: DB_MOCK_DATA
          value: "true"
        - name: REDIS_HOST
          value: "tb-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DATABASE
          value: "0"
        - name: JWT_SIGNER
          value: "test@test.com"
        - name: JWT_SECRET
          value: "dGVzdHRlc3R0ZXN0dGVzdAo="
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  type: ClusterIP
  selector:
    app: ratings
  ports:
  - port: 8080
    name: ratings
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/ratings/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ratings
                port:
                  number: 8080
